# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a6b24679c30c54e05b5a972a093578753a81fd58448a9917f5eecc5455ddb0f6efa8a07bc65eaf5dfab4feb934722ab3885c92bc9f23017c0654f23feebe2cc

test:
  secret_key_base: 9cff592b21b87ef29b73554a32ba1a4ac3ee9c9d2a31337a4a697ad45de9639a19f73de6a8f04797c592614b6d92c5905334ec08cb7cb817ea14aafe70f70f5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7a6b24679c30c54e05b5a972a093578753a81fd58448a9917f5eecc5455ddb0f6efa8a07bc65eaf5dfab4feb934722ab3885c92bc9f23017c0654f23feebe2cc

